/// Conformance is generated by the `@FeatureState` macro. Do not conform manually.
public protocol FeatureStateProtocol {
    /// A key-path namespace mirroring the view-visible members of the state type.
    /// Never instantiated; exists so that projections can be indexed with compile-time
    /// member checking that excludes domain-only and private members.
    associatedtype _ViewMembers

    /// Maps a namespace key path to the corresponding key path on the state type.
    /// `@MainActor`: key paths are not `Sendable`, so the stored map must be isolated;
    /// every reader (projection, `_commit`, `_diff`) is already MainActor-confined.
    @MainActor
    static var _viewKeyPaths: [PartialKeyPath<_ViewMembers>: AnyKeyPath] { get }

    /// The subset of `_ViewMembers` key paths whose members are computed — derived view
    /// output. The projection serves these from the registrar's derivation cache (seeding
    /// on first read); stored members read straight through committed state. Enum case
    /// accessors are deliberately excluded: they read through.
    @MainActor
    static var _derivedMembers: Set<PartialKeyPath<_ViewMembers>> { get }

    /// The generated reducer: diff each view-visible member of `old` against `new` and
    /// fire `registrar` for every member whose value or derived output changed.
    /// `key` is the projection-key prefix under which this value lives (root for the
    /// host's own state; extended per member/element when nested).
    @MainActor
    static func _commit(
        old: Self, new: Self,
        registrar: FeatureStateRegistrar, key: ProjectionKey
    )
}
