/// A value state's generated, view-visible member namespace.
///
/// This protocol adds no Sendable, Equatable, or Observation requirement.
/// Conformance is generated by `@FeatureState`.
public protocol FeatureStateProtocol {
    associatedtype _ViewMembers

    @MainActor
    static var _viewMembers: _ViewMembers { get }

    @MainActor
    static func _commit(old: Self, new: Self, registrar: FeatureStateRegistrar, key: ProjectionKey)
}
